### ISSUE TITLE
Android Plugin Crash

### ISSUE THREAD

**Issue by doomed2020** [AdvancedHacker101/android-c-sharp-rat-server#2]
Hi,

This issue occurs after executing android extension from the app. After I start listening on an Android Port and then close the "Android Plugin Window" and re-open it by pressing "Execute, it again asks to enter the Port, If I enter the same Port, the app crashes. I think that is caused due to same Port being used to Listen. While It should Stop the Listening port of Android when the "Plugin Window" is closed or it should not ask to enter Port again.

The whole app needs to be closed and then re-opened to use the android plugin again.

**Comment by AdvancedHacker101** [comment]
Thanks for pointing out the issue!
I will see what can I do about that.
I think it's better if we can close, then re-open the window, so i won't stop listening while the window is closed, but insted implement functions to handle the re-opening of the plugin.

**Comment by doomed2020** [comment]
Edit: Just found the Right Click Option to Rotate the Image 😄 . Also can you tell me the Default Path of Audio and Video Recording?

_Another issue, probably not so Critical one, is the Camera angle, If I hold the Mobile Vertically, the Picture show in "Image View" is Horizontal (inverted 90*). It probably has to do with some Camera Hardware placement._ 

_https://stackoverflow.com/questions/3841122/android-camera-preview-is-sideways_

**Comment by AdvancedHacker101** [comment]
Video Recording stored at: externalStorageDirPath/ahmedia/vid.mp4  
Audio recording stored at the same place, just named record.3pg  
The external storage path is retrieved from an envrionment variable, so it can be different on phones.  
In ES FileExplorer a free android app you can get to the external storage path by swiping right and from the *Local* menu select internal storage.  
The naming is confusing. External Storage doesn't mean it's on an SD Card. In android internal storage is where applications and their data is stored, external storage is where other data: downloads, music, files are stored.  
Hope this helps you!

**Comment by AdvancedHacker101** [comment]
Hi!
I just pushed a verison which allows the AndroidUI to be backgrounded and with execut foregrounded again! Some of the required code is in the sCore.dll, but its source is not on github yet!  
You can check out the changes here:  
97f7d61a61dda780e96bdbf344827744402012a0
